# Generated by Django 4.1.10 on 2023-10-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='oder',
            new_name='order',
        ),
    ]
